name: PipelineWorkflow01

on:
  push:
    branches:
      - main
  #pull_requests:
    #branches:
     # - main

jobs:
  builds:
    name: Azure Pipeline
    run-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url:  https://dev.azure.com/Projects-Organization/IOSv1.0
        azure-pipeline-name:  'webtestapp'
        azure-devops-token:  ${{ secrets.AZURE_DEVOPS_TOKEN }}
